### ISSUE TITLE
Add audit log viewer UI

### ISSUE THREAD

**Issue by jvz** [jenkinsci/audit-log-plugin#32]
A UI somewhat similar to the existing Jenkins log viewer should be made for recording and viewing audit log events from a webpage.

**Comment by gayathrirajendar** [comment]
Hello @jvz, 

I'm interested to take up this task. May I get some initial help here?

**Comment by jvz** [comment]
Take a look at LogRecorder and its supporting code in Jenkins core: https://github.com/jenkinsci/jenkins/tree/master/core/src/main/resources/hudson/logging/LogRecorder

I'd like to have a UI vaguely similar to this that you can view audit events captured during the lifetime of Jenkins. One idea I'd suggest would be configuring an additional appender to save log events that only takes audit log events. This may actually require the creation of a custom log4j2 appender similar to ListAppender: https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/test/java/org/apache/logging/log4j/test/appender/ListAppender.java
