### ISSUE TITLE
Improve existing tests

### ISSUE THREAD

**Issue by jvz** [jenkinsci/audit-log-plugin#38]
Current test coverage only asserts the number of audit events created via different test scenarios. These tests can be improved to assert that the audit events being logged match the expected data being used in the test. This should also make the tests less prone to failure when more audit events are defined in the system.

**Comment by aarthira** [comment]
As I experienced the test issues before, I will work on improving it.

**Comment by jvz** [comment]
Now you can apply similar refactoring to the user tests, or you can defer that, close this, and move on to the next task.

**Comment by jvz** [comment]
This looked like we were done. If I closed this too early, please let me know.
