### ISSUE TITLE
Audit Logs Filling Disk

### ISSUE THREAD

**Issue by bigedd6513** [jenkinsci/audit-log-plugin#71]
The audit logs end up filling up all available disk space, can we get some retention configuration options added?

**Comment by bitwiseman** [comment]
@bigedd6513  Could you be a bit more specific?  How can we reproduce this?

**Comment by bigedd6513** [comment]
This plugin generates audit log files in the file system in the ${JENKINS_HOME}/logs directory right? I have been seeing those logs continue to grow indefinitely and eat up disk space. Is there anyway to clean these up automatically via plugin configuration.

**Comment by jvz** [comment]
As a workaround, you can copy the https://github.com/jenkinsci/audit-log-plugin/blob/master/src/main/resources/log4j2.xml config from the plugin and add a DefaultRolloverStrategy with a max number of files. See log4j manual: https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingRandomAccessFileAppender

Then specify the system property to Jenkins `log4j2.configurationFile=path/to/log4j2.xml`

**Comment by jvz** [comment]
I'm updating this plugin to default to keeping up to 30 log files (rolling). A proper configuration UI would be nice, though there are a lot of options to potentially expose here.
