### ISSUE TITLE
Audit logs "source_host" identifier

### ISSUE THREAD

**Issue by vickycool91** [jenkinsci/audit-log-plugin#73]
Hi Team,
As a part of extracting data from audit logs, we are looking for a field "source_host" that would give the value of the source Jenkins URL it is pointing to. For e.g, if there are many events recorded for a build trigger, then how the "source_host" field gets the value. Let me know if you could provide further insights on this or anything else required from my end.

**Comment by vickycool91** [comment]
Hi team, Any update on mentioned issue? Let me know in case additional information is required from my end.

**Comment by jvz** [comment]
Can you provide a little more detail about how you'd want this to integrate with existing audit events defined?

**Comment by jvz** [comment]
Ah I see, simple enough. That would make sense as a common audit attribute for all events. Now which hostname to use though? Every non-trivial machine will have multiple hostnames and IP addresses (the trivial case being a disconnected computer with only localhost/loopback enabled). Are you thinking the result of `InetAddress.getLocalHost()` which tries to do a reverse lookup on itself? Or some other source like from the HTTP request?

**Comment by vickycool91** [comment]
Hostname should be the one where the Jenkins instance is running. For e.g: If I install the jenkins in my local desktop on a port 8088, then source_host should display the value as https://localhost:8088/. Likewise, wherever the Jenkins instance runs, the complete https url should be printed.

**Comment by jvz** [comment]
Oh so the Jenkins root URL basically? Since that might be different than the server's own hostname due to reverse proxies, ingress nodes, or whatever network topology you have. I think this makes sense.

**Comment by vickycool91** [comment]
May I know in which plugin version this enhancement would be available and probable date of release of the plugin ?

**Comment by jvz** [comment]
It's in 1.2, already released. It's in the requestUri attribute as that was supposed to be supported by now as it is. Let me know if you'd also like a separate field for just the hostname, though I think this might be sufficient.
